"""empty message

Revision ID: 4622cb82c2e7
Revises: 2055ff19815c
Create Date: 2025-08-24 20:52:36.681344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4622cb82c2e7'
down_revision = '2055ff19815c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('followers', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['follower_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['followed_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('followers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
